export const CRITERIA_POOLS = {
    directors: [
        { id: '138', label: 'Quentin Tarantino', value: 'Quentin Tarantino', tmdbId: 138, type: 'director' },
        { id: '525', label: 'Christopher Nolan', value: 'Christopher Nolan', tmdbId: 525, type: 'director' },
        { id: '240', label: 'Stanley Kubrick', value: 'Stanley Kubrick', tmdbId: 240, type: 'director' },
        { id: '488', label: 'Steven Spielberg', value: 'Steven Spielberg', tmdbId: 488, type: 'director' },
        { id: '1032', label: 'Martin Scorsese', value: 'Martin Scorsese', tmdbId: 1032, type: 'director' },
        { id: '2710', label: 'James Cameron', value: 'James Cameron', tmdbId: 2710, type: 'director' },
        { id: '17058', label: 'Greta Gerwig', value: 'Greta Gerwig', tmdbId: 17058, type: 'director' },
        { id: '3223', label: 'Robert Zemeckis', value: 'Robert Zemeckis', tmdbId: 3223, type: 'director' },
        { id: '7467', label: 'David Fincher', value: 'David Fincher', tmdbId: 7467, type: 'director' },
        { id: '303', label: 'Ridley Scott', value: 'Ridley Scott', tmdbId: 303, type: 'director' },
        { id: '1', label: 'George Lucas', value: 'George Lucas', tmdbId: 1, type: 'director' },
        { id: '7238', label: 'Hayao Miyazaki', value: 'Hayao Miyazaki', tmdbId: 7238, type: 'director' },
        { id: '1223', label: 'Joel Coen', value: 'Joel Coen', tmdbId: 1223, type: 'director' },
        { id: '105', label: 'Francis Ford Coppola', value: 'Francis Ford Coppola', tmdbId: 105, type: 'director' },
        { id: '21684', label: 'Bong Joon-ho', value: 'Bong Joon-ho', tmdbId: 21684, type: 'director' },
        { id: '5602', label: 'David Lynch', value: 'David Lynch', tmdbId: 5602, type: 'director' },
        { id: '289', label: 'Wes Anderson', value: 'Wes Anderson', tmdbId: 289, type: 'director' },
        { id: '137427', label: "Denis Villeneuve", value: "Denis Villeneuve", tmdbId: 137427, type: 'director' },
        { id: '11218', label: "Alfonso Cuarón", value: "Alfonso Cuarón", tmdbId: 11218, type: 'director' },
        { id: '190', label: "Clint Eastwood", value: "Clint Eastwood", tmdbId: 190, type: 'director' },
        { id: '9340', label: "Lana Wachowski", value: "Lana Wachowski", tmdbId: 9340, type: 'director' },
        { id: '9339', label: "Lilly Wachowski", value: "Lilly Wachowski", tmdbId: 9339, type: 'director' },
        { id: '59', label: "Luc Besson", value: "Luc Besson", tmdbId: 59, type: 'director' },
        { id: '108', label: "Peter Jackson", value: "Peter Jackson", tmdbId: 108, type: 'director' },
        { id: '510', label: "Tim Burton", value: "Tim Burton", tmdbId: 510, type: 'director' },
        { id: '865', label: "Michael Bay", value: "Michael Bay", tmdbId: 865, type: 'director' },
        { id: '10828', label: "Guillermo del Toro", value: "Guillermo del Toro", tmdbId: 10828, type: 'director' },
        { id: '67367', label: "Rian Johnson", value: "Rian Johnson", tmdbId: 67367, type: 'director' },
        { id: '15344', label: "J. J. Abrams", value: "J.J. Abrams", tmdbId: 15344, type: 'director' },
    ],
    actors: [
        { id: '287', label: 'Brad Pitt', value: 'Brad Pitt', tmdbId: 287, type: 'actor' },
        { id: '6193', label: 'Leonardo DiCaprio', value: 'Leonardo DiCaprio', tmdbId: 6193, type: 'actor' },
        { id: '500', label: 'Tom Cruise', value: 'Tom Cruise', tmdbId: 500, type: 'actor' },
        { id: '31', label: 'Tom Hanks', value: 'Tom Hanks', tmdbId: 31, type: 'actor' },
        { id: '12835', label: 'Vin Diesel', value: 'Vin Diesel', tmdbId: 12835, type: 'actor' },
        { id: '18897', label: 'Jackie Chan', value: 'Jackie Chan', tmdbId: 18897, type: 'actor' },
        { id: '72129', label: 'Jennifer Lawrence', value: 'Jennifer Lawrence', tmdbId: 72129, type: 'actor' },
        { id: '1245', label: 'Scarlett Johansson', value: 'Scarlett Johansson', tmdbId: 1245, type: 'actor' },
        { id: '976', label: 'Jason Statham', value: 'Jason Statham', tmdbId: 976, type: 'actor' },
        { id: '18918', label: 'Dwayne Johnson', value: 'Dwayne Johnson', tmdbId: 18918, type: 'actor' },
        { id: '11701', label: 'Angelina Jolie', value: 'Angelina Jolie', tmdbId: 11701, type: 'actor' },
        { id: '71580', label: 'Gal Gadot', value: 'Gal Gadot', tmdbId: 71580, type: 'actor' },
        { id: '224513', label: 'Ana de Armas', value: 'Ana de Armas', tmdbId: 224513, type: 'actor' },
        { id: '131', label: 'Jake Gyllenhaal', value: 'Jake Gyllenhaal', tmdbId: 131, type: 'actor' },
        { id: '6968', label: 'Hugh Jackman', value: 'Hugh Jackman', tmdbId: 6968, type: 'actor' },
        { id: '85', label: 'Johnny Depp', value: 'Johnny Depp', tmdbId: 85, type: 'actor' },
        { id: '6384', label: 'Keanu Reeves', value: 'Keanu Reeves', tmdbId: 6384, type: 'actor' },
        { id: '1269', label: 'Will Smith', value: 'Will Smith', tmdbId: 1269, type: 'actor' },
        { id: '3485', label: 'Emma Watson', value: 'Emma Watson', tmdbId: 3485, type: 'actor' },
        { id: '1136406', label: 'Tom Holland', value: 'Tom Holland', tmdbId: 1136406, type: 'actor' },
        { id: '3223', label: 'Robert Downey Jr.', value: 'Robert Downey Jr.', tmdbId: 3223, type: 'actor' },
        { id: '73968', label: 'Henry Cavill', value: 'Henry Cavill', tmdbId: 73968, type: 'actor' },
        { id: '192', label: 'Morgan Freeman', value: 'Morgan Freeman', tmdbId: 192, type: 'actor' },
        { id: '3896', label: 'Liam Neeson', value: 'Liam Neeson', tmdbId: 3896, type: 'actor' },
        { id: '1892', label: 'Matt Damon', value: 'Matt Damon', tmdbId: 1892, type: 'actor' },
        { id: '3894', label: 'Christian Bale', value: 'Christian Bale', tmdbId: 3894, type: 'actor' },
        { id: '880', label: "Ben Affleck", value: "Ben Affleck", tmdbId: 880, type: 'actor' },
        { id: '13560', label: "Julianne Moore", value: "Julianne Moore", tmdbId: 13560, type: 'actor' },
        { id: '2296', label: "Clive Owen", value: "Clive Owen", tmdbId: 2296, type: 'actor' },
        { id: '1461', label: "George Clooney", value: "George Clooney", tmdbId: 1461, type: 'actor' },
        { id: '18277', label: "Sandra Bullock", value: "Sandra Bullock", tmdbId: 18277, type: 'actor' },
        { id: '30614', label: "Ryan Gosling", value: "Ryan Gosling", tmdbId: 30614, type: 'actor' },
        { id: '10859', label: "Ryan Reynolds", value: "Ryan Reynolds", tmdbId: 10859, type: 'actor' },
        { id: '3895', label: "Channing Tatum", value: "Channing Tatum", tmdbId: 3895, type: 'actor' },
        { id: '10980', label: "Daniel Radcliffe", value: "Daniel Radcliffe", tmdbId: 10980, type: 'actor' },
        { id: '51329', label: "Bradley Cooper", value: "Bradley Cooper", tmdbId: 51329, type: 'actor' },
        { id: '10694', label: "Michael Peña", value: "Michael Peña", tmdbId: 10694, type: 'actor' },
        { id: '179', label: "Andy Garcia", value: "Andy Garcia", tmdbId: 179, type: 'actor' },
        { id: '2975', label: "Laurence Fishburne", value: "Laurence Fishburne", tmdbId: 2975, type: 'actor' },
        { id: '530', label: "Carrie-Anne Moss", value: "Carrie-Anne Moss", tmdbId: 530, type: 'actor' },
        { id: '1331', label: "Hugo Weaving", value: "Hugo Weaving", tmdbId: 1331, type: 'actor' },
        { id: '532', label: "Joe Pantoliano", value: "Joe Pantoliano", tmdbId: 532, type: 'actor' },
        { id: '524', label: "Natalie Portman", value: "Natalie Portman", tmdbId: 524, type: 'actor' },
        { id: '4391', label: "Jean Reno", value: "Jean Reno", tmdbId: 4391, type: 'actor' },
        { id: '64', label: "Gary Oldman", value: "Gary Oldman", tmdbId: 64, type: 'actor' },
        { id: '18973', label: "Mila Kunis", value: "Mila Kunis", tmdbId: 18973, type: 'actor' },
        { id: '62', label: "Bruce Willis", value: "Bruce Willis", tmdbId: 62, type: 'actor' },
        { id: '63', label: "Milla Jovovich", value: "Milla Jovovich", tmdbId: 63, type: 'actor' },
        { id: '65', label: "Ian Holm", value: "Ian Holm", tmdbId: 65, type: 'actor' },
        { id: '109', label: "Elijah Wood", value: "Elijah Wood", tmdbId: 109, type: 'actor' },
        { id: '1327', label: "Ian McKellen", value: "Ian McKellen", tmdbId: 1327, type: 'actor' },
        { id: '110', label: "Viggo Mortensen", value: "Viggo Mortensen", tmdbId: 110, type: 'actor' },
        { id: '1682', label: "Liv Tyler", value: "Liv Tyler", tmdbId: 1682, type: 'actor' },
        { id: '114', label: "Orlando Bloom", value: "Orlando Bloom", tmdbId: 114, type: 'actor' },
        { id: '112', label: "Cate Blanchett", value: "Cate Blanchett", tmdbId: 112, type: 'actor' },
        { id: '1328', label: "Sean Astin", value: "Sean Astin", tmdbId: 1328, type: 'actor' },
        { id: '48', label: "Sean Bean", value: "Sean Bean", tmdbId: 48, type: 'actor' },
        { id: '113', label: "Christopher Lee", value: "Christopher Lee", tmdbId: 113, type: 'actor' },
        { id: '1333', label: "Andy Serkis", value: "Andy Serkis", tmdbId: 1333, type: 'actor' },
        { id: '1372', label: "Karl Urban", value: "Karl Urban", tmdbId: 1372, type: 'actor' },
        { id: '70851', label: "Jack Black", value: "Jack Black", tmdbId: 70851, type: 'actor' },
        { id: '3489', label: "Naomi Watts", value: "Naomi Watts", tmdbId: 3489, type: 'actor' },
        { id: '3490', label: "Adrien Brody", value: "Adrien Brody", tmdbId: 3490, type: 'actor' },
        { id: '7060', label: "Martin Freeman", value: "Martin Freeman", tmdbId: 7060, type: 'actor' },
        { id: '71580', label: "Benedict Cumberbatch", value: "Benedict Cumberbatch", tmdbId: 71580, type: 'actor' },
        { id: '2232', label: "Michael Keaton", value: "Michael Keaton", tmdbId: 2232, type: 'actor' },
        { id: '1920', label: "Winona Ryder", value: "Winona Ryder", tmdbId: 1920, type: 'actor' },
        { id: '7447', label: "Alec Baldwin", value: "Alec Baldwin", tmdbId: 7447, type: 'actor' },
        { id: '76070', label: "Mia Wasikowska", value: "Mia Wasikowska", tmdbId: 76070, type: 'actor' },
        { id: '1283', label: "Helena Bonham Carter", value: "Helena Bonham Carter", tmdbId: 1283, type: 'actor' },
        { id: '1813', label: "Anne Hathaway", value: "Anne Hathaway", tmdbId: 1813, type: 'actor' },
        { id: '514', label: "Jack Nicholson", value: "Jack Nicholson", tmdbId: 514, type: 'actor' },
        { id: '4690', label: "Christopher Walken", value: "Christopher Walken", tmdbId: 4690, type: 'actor' },
        { id: '6730', label: "Sacha Baron Cohen", value: "Sacha Baron Cohen", tmdbId: 6730, type: 'actor' },
        { id: '3061', label: "Ewan McGregor", value: "Ewan McGregor", tmdbId: 3061, type: 'actor' },
        { id: '1160', label: "Michelle Pfeiffer", value: "Michelle Pfeiffer", tmdbId: 1160, type: 'actor' },
        { id: '77996', label: "Asa Butterfield", value: "Asa Butterfield", tmdbId: 77996, type: 'actor' },
        { id: '989325', label: "Ella Purnell", value: "Ella Purnell", tmdbId: 989325, type: 'actor' },
        { id: '10912', label: "Eva Green", value: "Eva Green", tmdbId: 10912, type: 'actor' },
        { id: '2231', label: "Samuel L. Jackson", value: "Samuel L. Jackson", tmdbId: 2231, type: 'actor' },
        { id: '5309', label: "Judi Dench", value: "Judi Dench", tmdbId: 5309, type: 'actor' },
        { id: '290', label: "Christopher Plummer", value: "Christopher Plummer", tmdbId: 290, type: 'actor' },
        { id: '6161', label: "Jennifer Connelly", value: "Jennifer Connelly", tmdbId: 6161, type: 'actor' },
        { id: '4764', label: "John C. Reilly", value: "John C. Reilly", tmdbId: 4764, type: 'actor' },
        { id: '56734', label: "Chloë Grace Moretz", value: "Chloë Grace Moretz", tmdbId: 56734, type: 'actor' },
        { id: '1532', label: "Bill Murray", value: "Bill Murray", tmdbId: 1532, type: 'actor' },
        { id: '19537', label: "Megan Fox", value: "Megan Fox", tmdbId: 19537, type: 'actor' },
        { id: '10959', label: "Shia LaBeouf", value: "Shia LaBeouf", tmdbId: 10959, type: 'actor' },
        { id: '1241', label: "John Turturro", value: "John Turturro", tmdbId: 1241, type: 'actor' },
        { id: '13240', label: "Mark Wahlberg", value: "Mark Wahlberg", tmdbId: 13240, type: 'actor' },
        { id: '4173', label: "Anthony Hopkins", value: "Anthony Hopkins", tmdbId: 4173, type: 'actor' },
        { id: '2283', label: "Stanley Tucci", value: "Stanley Tucci", tmdbId: 2283, type: 'actor' },
        { id: '130640', label: "Hailee Steinfeld", value: "Hailee Steinfeld", tmdbId: 130640, type: 'actor' },
        { id: '6949', label: "John Malkovich", value: "John Malkovich", tmdbId: 6949, type: 'actor' },
        { id: '83586', label: "Ken Jeong", value: "Ken Jeong", tmdbId: 83586, type: 'actor' },
        { id: '884', label: "Steve Buscemi", value: "Steve Buscemi", tmdbId: 884, type: 'actor' },
        { id: '887', label: "Owen Wilson", value: "Owen Wilson", tmdbId: 887, type: 'actor' },
        { id: '61981', label: "Michael Clarke Duncan", value: "Michael Clarke Duncan", tmdbId: 61981, type: 'actor' },
        { id: '53', label: "Peter Stormare", value: "Peter Stormare", tmdbId: 53, type: 'actor' },
        { id: '938', label: "Djimon Hounsou", value: "Djimon Hounsou", tmdbId: 938, type: 'actor' },
        { id: '74568', label: "Chris Hemsworth", value: "Chris Hemsworth", tmdbId: 74568, type: 'actor' },
        { id: '2299', label: "Josh Hartnett", value: "Josh Hartnett", tmdbId: 2299, type: 'actor' },
        { id: '3967', label: "Kate Beckinsale", value: "Kate Beckinsale", tmdbId: 3967, type: 'actor' },
        { id: '10127', label: "Jon Voight", value: "Jon Voight", tmdbId: 10127, type: 'actor' },
        { id: '738', label: "Sean Connery", value: "Sean Connery", tmdbId: 738, type: 'actor' },
        { id: '2963', label: "Nicolas Cage", value: "Nicolas Cage", tmdbId: 2963, type: 'actor' },
        { id: '228', label: "Ed Harris", value: "Ed Harris", tmdbId: 228, type: 'actor' },
        { id: '1620', label: "Michelle Yeoh", value: "Michelle Yeoh", tmdbId: 1620, type: 'actor' },
        { id: '17697', label: "John Krasinski", value: "John Krasinski", tmdbId: 17697, type: 'actor' },
        { id: '335', label: "Michael Shannon", value: "Michael Shannon", tmdbId: 335, type: 'actor' },
        { id: '53650', label: "Anthony Mackie", value: "Anthony Mackie", tmdbId: 53650, type: 'actor' },
        { id: '78029', label: "Martin Lawrence", value: "Martin Lawrence", tmdbId: 78029, type: 'actor' },
        { id: '10860', label: "Jessica Biel", value: "Jessica Biel", tmdbId: 10860, type: 'actor' },
        { id: '5081', label: "Emily Blunt", value: "Emily Blunt", tmdbId: 5081, type: 'actor' },
        { id: '569', label: "Ethan Hawke", value: "Ethan Hawke", tmdbId: 569, type: 'actor' },
        { id: '2037', label: "Cillian Murphy", value: "Cillian Murphy", tmdbId: 2037, type: 'actor' },
        { id: '27319', label: "Christoph Waltz", value: "Christoph Waltz", tmdbId: 27319, type: 'actor' },
        { id: '39658', label: "Sally Hawkins", value: "Sally Hawkins", tmdbId: 39658, type: 'actor' },
        { id: '6944', label: "Octavia Spencer", value: "Octavia Spencer", tmdbId: 6944, type: 'actor' },
        { id: '2372', label: "Ron Perlman", value: "Ron Perlman", tmdbId: 2372, type: 'actor' },
        { id: '3063', label: "Tilda Swinton", value: "Tilda Swinton", tmdbId: 3063, type: 'actor' },
        { id: '11180', label: "David Bradley", value: "David Bradley", tmdbId: 11180, type: 'actor' },
        { id: '5049', label: "John Hurt", value: "John Hurt", tmdbId: 5049, type: 'actor' },
        { id: '17605', label: "Idris Elba", value: "Idris Elba", tmdbId: 17605, type: 'actor' },
        { id: '83002', label: "Jessica Chastain", value: "Jessica Chastain", tmdbId: 83002, type: 'actor' },
        { id: '91606', label: "Tom Hiddleston", value: "Tom Hiddleston", tmdbId: 91606, type: 'actor' },
        { id: '3051', label: "Toni Collette", value: "Toni Collette", tmdbId: 3051, type: 'actor' },
        { id: '5293', label: "Willem Dafoe", value: "Willem Dafoe", tmdbId: 5293, type: 'actor' },
        { id: '1341', label: "Donnie Yen", value: "Donnie Yen", tmdbId: 1341, type: 'actor' },
        { id: '8784', label: "Daniel Craig", value: "Daniel Craig", tmdbId: 8784, type: 'actor' },
        { id: '16828', label: "Chris Evans", value: "Chris Evans", tmdbId: 16828, type: 'actor' },
        { id: '8944', label: "Jamie Lee Curtis", value: "Jamie Lee Curtis", tmdbId: 8944, type: 'actor' },
        { id: '16851', label: "Josh Brolin", value: "Josh Brolin", tmdbId: 16851, type: 'actor' },
        { id: '125660', label: "Andrew Scott", value: "Andrew Scott", tmdbId: 125660, type: 'actor' },
        { id: '515', label: "Glenn Close", value: "Glenn Close", tmdbId: 515, type: 'actor' },
        { id: '17604', label: "Jeremy Renner", value: "Jeremy Renner", tmdbId: 17604, type: 'actor' },
        { id: '1005852', label: "Janelle Monáe", value: "Janelle Monáe", tmdbId: 1005852, type: 'actor' },
        { id: '819', label: "Edward Norton", value: "Edward Norton", tmdbId: 819, type: 'actor' },
        { id: '543530', label: "Dave Bautista", value: "Dave Bautista", tmdbId: 543530, type: 'actor' },
        { id: '1202689', label: "Jessica Henwick", value: "Jessica Henwick", tmdbId: 1202689, type: 'actor' },
        { id: '3291', label: "Hugh Grant", value: "Hugh Grant", tmdbId: 3291, type: 'actor' },
        { id: '1315036', label: "Daisy Ridley", value: "Daisy Ridley", tmdbId: 1315036, type: 'actor' },
        { id: '2', label: "Mark Hamill", value: "Mark Hamill", tmdbId: 2, type: 'actor' },
        { id: '236695', label: "John Boyega", value: "John Boyega", tmdbId: 236695, type: 'actor' },
        { id: '1023139', label: "Adam Driver", value: "Adam Driver", tmdbId: 1023139, type: 'actor' },
        { id: '24045', label: "Joseph Gordon-Levitt", value: "Joseph Gordon-Levitt", tmdbId: 24045, type: 'actor' },
        { id: '17142', label: "Paul Dano", value: "Paul Dano", tmdbId: 17142, type: 'actor' },
        { id: '8447', label: "Jeff Daniels", value: "Jeff Daniels", tmdbId: 8447, type: 'actor' },
        { id: '72855', label: "Felicity Jones", value: "Felicity Jones", tmdbId: 72855, type: 'actor' },
        { id: '8688', label: "Diego Luna", value: "Diego Luna", tmdbId: 8688, type: 'actor' },
        { id: '1019', label: "Mads Mikkelsen", value: "Mads Mikkelsen", tmdbId: 1019, type: 'actor' },
        { id: '2178', label: "Forest Whitaker", value: "Forest Whitaker", tmdbId: 2178, type: 'actor' },
        { id: '103', label: "Mark Ruffalo", value: "Mark Ruffalo", tmdbId: 103, type: 'actor' },
        { id: '3293', label: "Rachel Weisz", value: "Rachel Weisz", tmdbId: 3293, type: 'actor' },
        { id: '1121', label: "Benicio del Toro", value: "Benicio del Toro", tmdbId: 1121, type: 'actor' },
        { id: '62064', label: "Chris Pine", value: "Chris Pine", tmdbId: 62064, type: 'actor' },
        { id: '11108', label: "Simon Pegg", value: "Simon Pegg", tmdbId: 11108, type: 'actor' },
        { id: '8691', label: "Zoe Saldaña", value: "Zoe Saldaña", tmdbId: 8691, type: 'actor' },
        { id: '68842', label: "John Cho", value: "John Cho", tmdbId: 68842, type: 'actor' },
        { id: '3', label: "Harrison Ford", value: "Harrison Ford", tmdbId: 3, type: 'actor' },
        { id: '3497', label: "Kyle Chandler", value: "Kyle Chandler", tmdbId: 3497, type: 'actor' },
        { id: '10182', label: "Ving Rhames", value: "Ving Rhames", tmdbId: 10182, type: 'actor' },
        { id: '1230', label: "John Goodman", value: "John Goodman", tmdbId: 1230, type: 'actor' },
        { id: '3872', label: "Daniel Brühl", value: "Daniel Brühl", tmdbId: 3872, type: 'actor' },
        { id: '1133349', label: "Elizabeth Debicki", value: "Elizabeth Debicki", tmdbId: 1133349, type: 'actor' },
        { id: '121529', label: "Léa Seydoux", value: "Léa Seydoux", tmdbId: 121529, type: 'actor' },
        { id: '933238', label: "Rebecca Ferguson", value: "Rebecca Ferguson", tmdbId: 933238, type: 'actor' },
        { id: '6807', label: "Sam Rockwell", value: "Sam Rockwell", tmdbId: 6807, type: 'actor' },
        { id: '62561', label: "Tessa Thompson", value: "Tessa Thompson", tmdbId: 62561, type: 'actor' },
        { id: '934', label: "Russell Crowe", value: "Russell Crowe", tmdbId: 934, type: 'actor' },
        { id: '4785', label: "Jeff Goldblum", value: "Jeff Goldblum", tmdbId: 4785, type: 'actor' },
        { id: '60073', label: "Brie Larson", value: "Brie Larson", tmdbId: 60073, type: 'actor' },
        { id: '22226', label: "Paul Rudd", value: "Paul Rudd", tmdbId: 22226, type: 'actor' },
        { id: '1896', label: "Don Cheadle", value: "Don Cheadle", tmdbId: 1896, type: 'actor' },
        { id: '550843', label: "Elizabeth Olsen", value: "Elizabeth Olsen", tmdbId: 550843, type: 'actor' },
        { id: '172069', label: "Chadwick Boseman", value: "Chadwick Boseman", tmdbId: 172069, type: 'actor' },
        { id: '73457', label: "Chris Pratt", value: "Chris Pratt", tmdbId: 73457, type: 'actor' },
        { id: '60898', label: "Sebastian Stan", value: "Sebastian Stan", tmdbId: 60898, type: 'actor' },
        { id: '12052', label: "Gwyneth Paltrow", value: "Gwyneth Paltrow", tmdbId: 12052, type: 'actor' },
        { id: '30082', label: "Benedict Wong", value: "Benedict Wong", tmdbId: 30082, type: 'actor' },
        { id: '543261', label: "Karen Gillan", value: "Karen Gillan", tmdbId: 543261, type: 'actor' },
        { id: '1810', label: "Heath Ledger", value: "Heath Ledger", tmdbId: 1810, type: 'actor' },
        { id: '6383', label: "Aaron Eckhart", value: "Aaron Eckhart", tmdbId: 6383, type: 'actor' },
        { id: '10297', label: "Matthew McConaughey", value: "Matthew McConaughey", tmdbId: 10297, type: 'actor' },
        { id: '1190668', label: "Timothée Chalamet", value: "Timothée Chalamet", tmdbId: 1190668, type: 'actor' },
        { id: '1373737', label: "Florence Pugh", value: "Florence Pugh", tmdbId: 1373737, type: 'actor' },
        { id: '76512', label: "Jason Clarke", value: "Jason Clarke", tmdbId: 76512, type: 'actor' },
        { id: '27578', label: "Elliot Page", value: "Elliot Page", tmdbId: 27578, type: 'actor' },
        { id: '11288', label: "Robert Pattinson", value: "Robert Pattinson", tmdbId: 11288, type: 'actor' },
        { id: '505710', label: "Zendaya", value: "Zendaya", tmdbId: 505710, type: 'actor' },
        { id: '2524', label: "Tom Hardy", value: "Tom Hardy", tmdbId: 2524, type: 'actor' },
        { id: '8293', label: "Marion Cotillard", value: "Marion Cotillard", tmdbId: 8293, type: 'actor' },
        { id: '1357546', label: "Ken Watanabe", value: "Ken Watanabe", tmdbId: 1357546, type: 'actor' },
        { id: '1117313', label: "John David Washington", value: "John David Washington", tmdbId: 1117313, type: 'actor' },
        { id: '11181', label: "Kenneth Branagh", value: "Kenneth Branagh", tmdbId: 11181, type: 'actor' },
        { id: '529', label: "Guy Pearce", value: "Guy Pearce", tmdbId: 529, type: 'actor' },
        { id: '1290466', label: "Barry Keoghan", value: "Barry Keoghan", tmdbId: 1290466, type: 'actor' },
        { id: '6162', label: "Paul Bettany", value: "Paul Bettany", tmdbId: 6162, type: 'actor' },
        { id: '51072', label: "Kate Mara", value: "Kate Mara", tmdbId: 51072, type: 'actor' },
        { id: '3810', label: "Javier Bardem", value: "Javier Bardem", tmdbId: 3810, type: 'actor' },
        { id: '1640', label: "Stellan Skarsgård", value: "Stellan Skarsgård", tmdbId: 1640, type: 'actor' },
        { id: '117642', label: "Jason Momoa", value: "Jason Momoa", tmdbId: 117642, type: 'actor' },
        { id: '86654', label: "Austin Butler", value: "Austin Butler", tmdbId: 86654, type: 'actor' },
        { id: '1110405', label: "Mackenzie Davis", value: "Mackenzie Davis", tmdbId: 1110405, type: 'actor' },
        { id: '7499', label: "Jared Leto", value: "Jared Leto", tmdbId: 7499, type: 'actor' },
        { id: '206919', label: "Daniel Kaluuya", value: "Daniel Kaluuya", tmdbId: 206919, type: 'actor' },
        { id: '9273', label: "Amy Adams", value: "Amy Adams", tmdbId: 9273, type: 'actor' },
        { id: '18288', label: "Terrence Howard", value: "Terrence Howard", tmdbId: 18288, type: 'actor' },
        { id: '11477', label: "Ray Liotta", value: "Ray Liotta", tmdbId: 11477, type: 'actor' },
        { id: '380', label: "Robert De Niro", value: "Robert De Niro", tmdbId: 380, type: 'actor' },
        { id: '4517', label: "Joe Pesci", value: "Joe Pesci", tmdbId: 4517, type: 'actor' },
        { id: '1038', label: "Jodie Foster", value: "Jodie Foster", tmdbId: 1038, type: 'actor' },
        { id: '21007', label: "Jonah Hill", value: "Jonah Hill", tmdbId: 21007, type: 'actor' },
        { id: '234352', label: "Margot Robbie", value: "Margot Robbie", tmdbId: 234352, type: 'actor' },
        { id: '88124', label: "Jesse Plemons", value: "Jesse Plemons", tmdbId: 88124, type: 'actor' },
        { id: '18269', label: "Brendan Fraser", value: "Brendan Fraser", tmdbId: 18269, type: 'actor' },
        { id: '2282', label: "Ben Kingsley", value: "Ben Kingsley", tmdbId: 2282, type: 'actor' },
        { id: '1158', label: "Al Pacino", value: "Al Pacino", tmdbId: 1158, type: 'actor' },
        { id: '1037', label: "Harvey Keitel", value: "Harvey Keitel", tmdbId: 1037, type: 'actor' },
        { id: '1115', label: "Stephen Graham", value: "Stephen Graham", tmdbId: 1115, type: 'actor' },
        { id: '37625', label: "Andrew Garfield", value: "Andrew Garfield", tmdbId: 37625, type: 'actor' },
        { id: '11856', label: "Daniel Day-Lewis", value: "Daniel Day-Lewis", tmdbId: 11856, type: 'actor' },
        { id: '6941', label: "Cameron Diaz", value: "Cameron Diaz", tmdbId: 6941, type: 'actor' },
        { id: '2039', label: "Brendan Gleeson", value: "Brendan Gleeson", tmdbId: 2039, type: 'actor' },
        { id: '9642', label: "Jude Law", value: "Jude Law", tmdbId: 9642, type: 'actor' },
        { id: '10205', label: "Sigourney Weaver", value: "Sigourney Weaver", tmdbId: 10205, type: 'actor' },
        { id: '73421', label: "Joaquin Phoenix", value: "Joaquin Phoenix", tmdbId: 73421, type: 'actor' },
        { id: '87722', label: "Noomi Rapace", value: "Noomi Rapace", tmdbId: 87722, type: 'actor' },
        { id: '17288', label: "Michael Fassbender", value: "Michael Fassbender", tmdbId: 17288, type: 'actor' },
        { id: '6885', label: "Charlize Theron", value: "Charlize Theron", tmdbId: 6885, type: 'actor' },
        { id: '1253360', label: "Pedro Pascal", value: "Pedro Pascal", tmdbId: 1253360, type: 'actor' },
        { id: '5292', label: "Denzel Washington", value: "Denzel Washington", tmdbId: 5292, type: 'actor' },
        { id: '77795', label: "Katherine Waterston", value: "Katherine Waterston", tmdbId: 77795, type: 'actor' },
        { id: '17051', label: "James Franco", value: "James Franco", tmdbId: 17051, type: 'actor' },
        { id: '5294', label: "Chiwetel Ejiofor", value: "Chiwetel Ejiofor", tmdbId: 5294, type: 'actor' },
        { id: '556356', label: "Vanessa Kirby", value: "Vanessa Kirby", tmdbId: 556356, type: 'actor' },
        { id: '8783', label: "Eric Bana", value: "Eric Bana", tmdbId: 8783, type: 'actor' },
        { id: '147', label: "Michael Madsen", value: "Michael Madsen", tmdbId: 147, type: 'actor' },
        { id: '1421138', label: "Mark Strong", value: "Mark Strong", tmdbId: 1421138, type: 'actor' },
        { id: '237405', label: "Lady Gaga", value: "Lady Gaga", tmdbId: 237405, type: 'actor' },
        { id: '955', label: "Penélope Cruz", value: "Penélope Cruz", tmdbId: 955, type: 'actor' },
        { id: '33192', label: "Joel Edgerton", value: "Joel Edgerton", tmdbId: 33192, type: 'actor' },
        { id: '1979', label: "Kevin Spacey", value: "Kevin Spacey", tmdbId: 1979, type: 'actor' },
        { id: '10882', label: "Rosamund Pike", value: "Rosamund Pike", tmdbId: 10882, type: 'actor' },
        { id: '44735', label: "Jesse Eisenberg", value: "Jesse Eisenberg", tmdbId: 44735, type: 'actor' },
        { id: '12111', label: "Justin Timberlake", value: "Justin Timberlake", tmdbId: 12111, type: 'actor' },
        { id: '3392', label: "Michael Douglas", value: "Michael Douglas", tmdbId: 3392, type: 'actor' },
        { id: '2228', label: "Sean Penn", value: "Sean Penn", tmdbId: 2228, type: 'actor' },
        { id: '32', label: "Robin Wright", value: "Robin Wright", tmdbId: 32, type: 'actor' },
        { id: '932967', label: "Mahershala Ali", value: "Mahershala Ali", tmdbId: 932967, type: 'actor' },
        { id: '4935', label: "Pete Postlethwaite", value: "Pete Postlethwaite", tmdbId: 4935, type: 'actor' },
        { id: '71070', label: "Amanda Seyfried", value: "Amanda Seyfried", tmdbId: 71070, type: 'actor' },
        { id: '37917', label: "Kristen Stewart", value: "Kristen Stewart", tmdbId: 37917, type: 'actor' },
        { id: '690', label: "Ke Huy Quan", value: "Ke Huy Quan", tmdbId: 690, type: 'actor' },
        { id: '65731', label: "Sam Worthington", value: "Sam Worthington", tmdbId: 65731, type: 'actor' },
        { id: '17647', label: "Michelle Rodriguez", value: "Michelle Rodriguez", tmdbId: 17647, type: 'actor' },
        { id: '204', label: "Kate Winslet", value: "Kate Winslet", tmdbId: 204, type: 'actor' },
        { id: '1100', label: "Arnold Schwarzenegger", value: "Arnold Schwarzenegger", tmdbId: 1100, type: 'actor' },
        { id: '25002', label: "Lee Byung-hun", value: "Lee Byung-hun", tmdbId: 25002, type: 'actor' },
        { id: '18999', label: "J.K. Simmons", value: "J.K. Simmons", tmdbId: 18999, type: 'actor' },
        { id: '18997', label: "Bryce Dallas Howard", value: "Bryce Dallas Howard", tmdbId: 18997, type: 'actor' },
        { id: '16483', label: "Sylvester Stallone", value: "Sylvester Stallone", tmdbId: 16483, type: 'actor' },
        { id: '215055', label: "Steven Yeun", value: "Steven Yeun", tmdbId: 215055, type: 'actor' },
        { id: '8891', label: "John Travolta", value: "John Travolta", tmdbId: 8891, type: 'actor' },
        { id: '139', label: "Uma Thurman", value: "Uma Thurman", tmdbId: 139, type: 'actor' },
        { id: '3129', label: "Tim Roth", value: "Tim Roth", tmdbId: 3129, type: 'actor' },
        { id: '140', label: "Lucy Liu", value: "Lucy Liu", tmdbId: 140, type: 'actor' },
        { id: '9824', label: "Diane Kruger", value: "Diane Kruger", tmdbId: 9824, type: 'actor' },
        { id: '134', label: "Jamie Foxx", value: "Jamie Foxx", tmdbId: 134, type: 'actor' },
        { id: '27740', label: "Walton Goggins", value: "Walton Goggins", tmdbId: 27740, type: 'actor' },
        { id: '501', label: "Dakota Fanning", value: "Dakota Fanning", tmdbId: 501, type: 'actor' },
        { id: '3905', label: "William H. Macy", value: "William H. Macy", tmdbId: 3905, type: 'actor' },
        { id: '5469', label: "Ralph Fiennes", value: "Ralph Fiennes", tmdbId: 5469, type: 'actor' },
        { id: '39995', label: "Michael Cera", value: "Michael Cera", tmdbId: 39995, type: 'actor' },
        { id: '53240', label: "Riz Ahmed", value: "Riz Ahmed", tmdbId: 53240, type: 'actor' },
        { id: '5064', label: "Meryl Streep", value: "Meryl Streep", tmdbId: 5064, type: 'actor' },
        { id: '1903874', label: "Maya Hawke", value: "Maya Hawke", tmdbId: 1903874, type: 'actor' },
        { id: '36592', label: "Saoirse Ronan", value: "Saoirse Ronan", tmdbId: 36592, type: 'actor' },
        { id: '3910', label: "Frances McDormand", value: "Frances McDormand", tmdbId: 3910, type: 'actor' },
        { id: '2176', label: "Tommy Lee Jones", value: "Tommy Lee Jones", tmdbId: 2176, type: 'actor' },
        { id: '57755', label: "Woody Harrelson", value: "Woody Harrelson", tmdbId: 57755, type: 'actor' },
        { id: '1229', label: "Jeff Bridges", value: "Jeff Bridges", tmdbId: 1229, type: 'actor' },
        { id: '205', label: "Kirsten Dunst", value: "Kirsten Dunst", tmdbId: 205, type: 'actor' },
        { id: '1356758', label: "Thomasin McKenzie", value: "Thomasin McKenzie", tmdbId: 1356758, type: 'actor' },
        { id: '5472', label: "Colin Firth", value: "Colin Firth", tmdbId: 5472, type: 'actor' },
        { id: '1922', label: "Catherine Zeta-Jones", value: "Catherine Zeta-Jones", tmdbId: 1922, type: 'actor' },
        { id: '35029', label: "David Harbour", value: "David Harbour", tmdbId: 35029, type: 'actor' },
        { id: '504', label: "Tim Robbins", value: "Tim Robbins", tmdbId: 504, type: 'actor' },
        { id: '2157', label: "Robin Williams", value: "Robin Williams", tmdbId: 2157, type: 'actor' },
        { id: '72466', label: "Colin Farrell", value: "Colin Farrell", tmdbId: 72466, type: 'actor' },
        { id: '2203', label: "Neal McDonough", value: "Neal McDonough", tmdbId: 2203, type: 'actor' },
        { id: '15440', label: "Jared Harris", value: "Jared Harris", tmdbId: 15440, type: 'actor' },
        { id: '116', label: "Keira Knightley", value: "Keira Knightley", tmdbId: 116, type: 'actor' },
        { id: '25072', label: "Oscar Isaac", value: "Oscar Isaac", tmdbId: 25072, type: 'actor' },
        { id: '3895', label: "Michael Caine", value: "Michael Caine", tmdbId: 3895, type: 'actor' },
        { id: '56731', label: "Jessica Alba", value: "Jessica Alba", tmdbId: 56731, type: 'actor' },
        { id: '17276', label: "Gerard Butler", value: "Gerard Butler", tmdbId: 17276, type: 'actor' },
        { id: '206', label: "Jim Carrey", value: "Jim Carrey", tmdbId: 206, type: 'actor' },
        { id: '2227', label: "Nicole Kidman", value: "Nicole Kidman", tmdbId: 2227, type: 'actor' },
        { id: '1204', label: "Julia Roberts", value: "Julia Roberts", tmdbId: 1204, type: 'actor' },
        { id: '19292', label: "Adam Sandler", value: "Adam Sandler", tmdbId: 19292, type: 'actor' },
        { id: '4491', label: "Jennifer Aniston", value: "Jennifer Aniston", tmdbId: 4491, type: 'actor' },
        { id: '93210', label: "Domhnall Gleeson", value: "Domhnall Gleeson", tmdbId: 93210, type: 'actor' },
        { id: '53714', label: "Rachel McAdams", value: "Rachel McAdams", tmdbId: 53714, type: 'actor' },
        { id: '54693', label: "Emma Stone", value: "Emma Stone", tmdbId: 54693, type: 'actor' },
        { id: '227454', label: "Alicia Vikander", value: "Alicia Vikander", tmdbId: 227454, type: 'actor' }
    ],
    genres: [
        { id: '28', label: 'Action', value: 28 },
        { id: '12', label: 'Adventure', value: 12 },
        { id: '16', label: 'Animation', value: 16 },
        { id: '35', label: 'Comedy', value: 35 },
        { id: '80', label: 'Crime', value: 80 },
        { id: '18', label: 'Drama', value: 18 },
        { id: '14', label: 'Fantasy', value: 14 },
        { id: '27', label: 'Horror', value: 27 },
        { id: '10749', label: 'Romance', value: 10749 },
        { id: '878', label: 'Sci-Fi', value: 878 },
        { id: '53', label: 'Thriller', value: 53 }
    ],
    decades: [
        { id: '1980s', label: '1980s', value: '1980-1989' },
        { id: '1990s', label: '1990s', value: '1990-1999' },
        { id: '2000s', label: '2000s', value: '2000-2009' },
        { id: '2010s', label: '2010s', value: '2010-2019' },
        { id: '2020s', label: '2020s', value: '2020-2029' }
    ],
    runtime: [
        { id: 'runtime_lt_90', label: 'Runtime < 90 Minutes', value: { max: 90 }, type: 'runtime' },
        { id: 'runtime_gt_150', label: 'Runtime > 2.5 Hours', value: { min: 150 }, type: 'runtime' },
        { id: 'runtime_gt_180', label: 'Runtime > 3 Hours', value: { min: 180 }, type: 'runtime' }
    ],
    revenue: [
        { id: 'rev_1b', label: 'Box Office > $1 Billion', value: { min: 1000000000 } },
        { id: 'rev_500m', label: 'Box Office > $500 Million', value: { min: 500000000 } }
    ],
    rating: [
        { id: 'pg_13', label: 'Rated PG-13', value: 'PG-13' },
        { id: 'r', label: 'Rated R', value: 'R' },
        { id: 'pg', label: 'Rated PG', value: 'PG' }
    ],
    companies: [
        { id: '41077', label: 'A24', value: 'A24', tmdbId: 41077, type: 'company' },
        { id: '420', label: 'Marvel Studios', value: 'Marvel Studios', tmdbId: 420, type: 'company' },
        { id: '174', label: 'Warner Bros. Pictures', value: 'Warner Bros.', tmdbId: 174, type: 'company' },
        { id: '33', label: 'Universal Pictures', value: 'Universal', tmdbId: 33, type: 'company' },
        { id: '2', label: 'Walt Disney Pictures', value: 'Disney', tmdbId: 2, type: 'company' },
        { id: '4', label: 'Paramount', value: 'Paramount', tmdbId: 4, type: 'company' },
        { id: '25', label: '20th Century Fox', value: '20th Century Fox', tmdbId: 25, type: 'company' },
        { id: '5', label: 'Columbia Pictures', value: 'Columbia Pictures', tmdbId: 5, type: 'company' },
        { id: '12', label: 'New Line Cinema', value: 'New Line Cinema', tmdbId: 12, type: 'company' },
        { id: '34', label: 'Sony Pictures', value: 'Sony', tmdbId: 34, type: 'company' },
        { id: '3', label: 'Pixar', value: 'Pixar', tmdbId: 3, type: 'company' },
        { id: '521', label: 'DreamWorks Animation', value: 'DreamWorks', tmdbId: 521, type: 'company' }
    ],
    keywords: [
        { id: '818', label: 'Based on Novel', value: 818 },
        { id: '9672', label: 'Based on True Story', value: 9672 },
        { id: '5565', label: 'Biography', value: 5565 },
        { id: '9717', label: 'Based on Comic', value: 9717 },
        { id: '180547', label: 'Marvel Cinematic Universe', value: 180547 },
        { id: '4379', label: 'Time Travel', value: 4379 },
        { id: '4565', label: 'Post-Apocalyptic', value: 4565 },
        { id: '169593', label: 'Space Opera', value: 169593 }
    ]
};
